[package]
name = "rusty-cl"
version = "0.1.0"
edition = "2021"
description = "Rusty binding for OpenCL"
authors = ["Felix Bytow <drako@drako.guru>"]
repository = "https://github.com/Drako/rusty-cl.git"
readme = "README.md"
license = "MIT"
links = "OpenCL"
build = "build.rs"

[workspace]
